openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: AWS X-Ray CreateGroup TimeSeriesServiceStatistics API
  description: Amazon Web Services X-Ray provides APIs for managing debug traces and retrieving service maps and other data created by processing those traces.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: xray
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/xray-2016-04-12.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://xray.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS X-Ray multi-region endpoint
- url: https://xray.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS X-Ray multi-region endpoint
- url: http://xray.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS X-Ray endpoint for China (Beijing) and China (Ningxia)
- url: https://xray.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS X-Ray endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: TimeSeriesServiceStatistics
paths:
  /TimeSeriesServiceStatistics:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetTimeSeriesServiceStatistics
      description: Get an aggregation of service statistics defined by a specific time range.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTimeSeriesServiceStatisticsResult'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: ThrottledException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottledException'
      parameters:
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - StartTime
              - EndTime
              properties:
                StartTime:
                  description: The start of the time frame for which to aggregate statistics.
                  type: string
                  format: date-time
                EndTime:
                  description: The end of the time frame for which to aggregate statistics.
                  type: string
                  format: date-time
                GroupName:
                  description: The case-sensitive name of the group for which to pull statistics from.
                  type: string
                  minLength: 1
                  maxLength: 32
                GroupARN:
                  description: The Amazon Resource Name (ARN) of the group for which to pull statistics from.
                  type: string
                  minLength: 1
                  maxLength: 400
                EntitySelectorExpression:
                  description: 'A filter expression defining entities that will be aggregated for statistics. Supports ID, service, and edge functions. If no selector expression is specified, edge statistics are returned. '
                  type: string
                  minLength: 1
                  maxLength: 500
                Period:
                  description: Aggregation period in seconds.
                  type: integer
                ForecastStatistics:
                  description: The forecasted high and low fault count values. Forecast enabled requests require the EntitySelectorExpression ID be provided.
                  type: boolean
                NextToken:
                  description: Pagination token.
                  type: string
      summary: Amazon X-Ray Get Time Series Service Statistics
      tags:
      - TimeSeriesServiceStatistics
components:
  schemas:
    String:
      type: string
    Boolean:
      type: boolean
    TimeSeriesServiceStatisticsList:
      type: array
      items:
        $ref: '#/components/schemas/TimeSeriesServiceStatistics'
    TimeSeriesServiceStatistics:
      type: object
      properties:
        Timestamp:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Timestamp of the window for which statistics are aggregated.
        EdgeSummaryStatistics:
          $ref: '#/components/schemas/EdgeStatistics'
        ServiceSummaryStatistics:
          $ref: '#/components/schemas/ServiceStatistics'
        ServiceForecastStatistics:
          allOf:
          - $ref: '#/components/schemas/ForecastStatistics'
          - description: The forecasted high and low fault count values.
        ResponseTimeHistogram:
          allOf:
          - $ref: '#/components/schemas/Histogram'
          - description: The response time histogram for the selected entities.
      description: A list of TimeSeriesStatistic structures.
    GetTimeSeriesServiceStatisticsResult:
      type: object
      properties:
        TimeSeriesServiceStatistics:
          allOf:
          - $ref: '#/components/schemas/TimeSeriesServiceStatisticsList'
          - description: The collection of statistics.
        ContainsOldGroupVersions:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: A flag indicating whether or not a group's filter expression has been consistent, or if a returned aggregation might show statistics from an older version of the group's filter expression.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Pagination token.
    EdgeStatistics:
      type: object
      properties:
        OkCount:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The number of requests that completed with a 2xx Success status code.
        ErrorStatistics:
          allOf:
          - $ref: '#/components/schemas/ErrorStatistics'
          - description: Information about requests that failed with a 4xx Client Error status code.
        FaultStatistics:
          allOf:
          - $ref: '#/components/schemas/FaultStatistics'
          - description: Information about requests that failed with a 5xx Server Error status code.
        TotalCount:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The total number of completed requests.
        TotalResponseTime:
          allOf:
          - $ref: '#/components/schemas/NullableDouble'
          - description: The aggregate response time of completed requests.
      description: Response statistics for an edge.
    Histogram:
      type: array
      items:
        $ref: '#/components/schemas/HistogramEntry'
    ServiceStatistics:
      type: object
      properties:
        OkCount:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The number of requests that completed with a 2xx Success status code.
        ErrorStatistics:
          allOf:
          - $ref: '#/components/schemas/ErrorStatistics'
          - description: Information about requests that failed with a 4xx Client Error status code.
        FaultStatistics:
          allOf:
          - $ref: '#/components/schemas/FaultStatistics'
          - description: Information about requests that failed with a 5xx Server Error status code.
        TotalCount:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The total number of completed requests.
        TotalResponseTime:
          allOf:
          - $ref: '#/components/schemas/NullableDouble'
          - description: The aggregate response time of completed requests.
      description: Response statistics for a service.
    Double:
      type: number
      format: double
    HistogramEntry:
      type: object
      properties:
        Value:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: The value of the entry.
        Count:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The prevalence of the entry.
      description: An entry in a histogram for a statistic. A histogram maps the range of observed values on the X axis, and the prevalence of each value on the Y axis.
    NullableDouble:
      type: number
      format: double
    ThrottledException: {}
    FaultStatistics:
      type: object
      properties:
        OtherCount:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The number of requests that failed with untracked 5xx Server Error status codes.
        TotalCount:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The total number of requests that failed with a 5xx Server Error status code.
      description: Information about requests that failed with a 5xx Server Error status code.
    InvalidRequestException: {}
    ForecastStatistics:
      type: object
      properties:
        FaultCountHigh:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The upper limit of fault counts for a service.
        FaultCountLow:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The lower limit of fault counts for a service.
      description: The predicted high and low fault count. This is used to determine if a service has become anomalous and if an insight should be created.
    ErrorStatistics:
      type: object
      properties:
        ThrottleCount:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The number of requests that failed with a 419 throttling status code.
        OtherCount:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The number of requests that failed with untracked 4xx Client Error status codes.
        TotalCount:
          allOf:
          - $ref: '#/components/schemas/NullableLong'
          - description: The total number of requests that failed with a 4xx Client Error status code.
      description: Information about requests that failed with a 4xx Client Error status code.
    Integer:
      type: integer
    Timestamp:
      type: string
      format: date-time
    NullableLong:
      type: integer
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/xray/
