openapi: 3.0.0
info:
  version: '2016-04-12'
  x-release: v4
  title: AWS X-Ray CreateGroup TelemetryRecords API
  description: Amazon Web Services X-Ray provides APIs for managing debug traces and retrieving service maps and other data created by processing those traces.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: xray
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/xray-2016-04-12.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://xray.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS X-Ray multi-region endpoint
- url: https://xray.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS X-Ray multi-region endpoint
- url: http://xray.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS X-Ray endpoint for China (Beijing) and China (Ningxia)
- url: https://xray.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS X-Ray endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: TelemetryRecords
paths:
  /TelemetryRecords:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: PutTelemetryRecords
      description: Used by the Amazon Web Services X-Ray daemon to upload telemetry.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutTelemetryRecordsResult'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: ThrottledException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottledException'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - TelemetryRecords
              properties:
                TelemetryRecords:
                  description: <p/>
                  type: array
                  items:
                    $ref: '#/components/schemas/TelemetryRecord'
                EC2InstanceId:
                  description: <p/>
                  type: string
                  maxLength: 20
                Hostname:
                  description: <p/>
                  type: string
                  maxLength: 255
                ResourceARN:
                  description: <p/>
                  type: string
                  maxLength: 500
      summary: Amazon X-Ray Put Telemetry Records
      tags:
      - TelemetryRecords
components:
  schemas:
    ThrottledException: {}
    InvalidRequestException: {}
    TelemetryRecord:
      type: object
      required:
      - Timestamp
      properties:
        Timestamp:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: <p/>
        SegmentsReceivedCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
        SegmentsSentCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
        SegmentsSpilloverCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
        SegmentsRejectedCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
        BackendConnectionErrors:
          allOf:
          - $ref: '#/components/schemas/BackendConnectionErrors'
          - description: <p/>
      description: <p/>
    PutTelemetryRecordsResult:
      type: object
      properties: {}
    Timestamp:
      type: string
      format: date-time
    NullableInteger:
      type: integer
    BackendConnectionErrors:
      type: object
      properties:
        TimeoutCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
        ConnectionRefusedCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
        HTTPCode4XXCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
        HTTPCode5XXCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
        UnknownHostCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
        OtherCount:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p/>
      description: <p/>
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/xray/
